config = {
    "attention_len": 48,
    "batch_size": 32,
    "output_size": 321,
    "dropout": 0.2,
    "file_out": "log.out",
    "horizon": 3,
    "learning_rate": 0.003,
    "max_gradient_norm": 5.0,
    "num_epoch": 20,
    "num_layers": 3,
    "num_units": 48,
    "num_highway": 48,
    "data_config": {
        "y": {
            "range": [1, 7],
            "key": ['label']
        },
        "x": {
            "range": [-47, 0],
            "key": ['day_month',
                    'rest_flag',
                    'holiday_flag',
                    'feat_month1',
                    'feat_month2',
                    'feat_month3',
                    'feat_month4',
                    'feat_month5',
                    'feat_month6',
                    'feat_month7',
                    'feat_month8',
                    'feat_month9',
                    'feat_month10',
                    'feat_month11',
                    'feat_month12',
                    'feat_day0',
                    'feat_day1',
                    'feat_day2',
                    'feat_day3',
                    'feat_day4',
                    'feat_day5',
                    'feat_day6',
                    'feat_holiday0',
                    'feat_holiday1',
                    'feat_holiday2',
                    'feat_holiday3',
                    'feat_holiday4',
                    'feat_holiday5',
                    'feat_holiday6',
                    'feat_holiday7',
                    'feat_holiday_aux0',
                    'feat_holiday_aux1',
                    'feat_holiday_aux2',
                    'feat_holiday_aux3',
                    'feat_holiday_aux4',
                    'feat_holiday_aux5',
                    'feat_holiday_aux6',
                    'feat_holiday_aux7',
                    'feat_holiday_aux8',
                    'feat_holiday_aux9',
                    'feat_holiday_aux10',
                    'feat_holiday_aux11',
                    'feat_holiday_aux12',
                    'feat_holiday_aux13',
                    'feat_holiday_aux14',
                    'feat_holiday_aux15',
                    ('weather_from', 'beijing'),
                    ('weather_from', 'chengdu'),
                    ('weather_from', 'chongqing'),
                    ('weather_from', 'guangzhou'),
                    ('weather_from', 'hangzhou'),
                    ('weather_from', 'nanjing'),
                    ('weather_from', 'shanghai'),
                    ('weather_from', 'shenzhen'),
                    ('weather_from', 'tianjin'),
                    ('weather_from', 'wuhan'),
                    ('weather_from', 'xian'),
                    ('weather_to', 'beijing'),
                    ('weather_to', 'chengdu'),
                    ('weather_to', 'chongqing'),
                    ('weather_to', 'guangzhou'),
                    ('weather_to', 'hangzhou'),
                    ('weather_to', 'nanjing'),
                    ('weather_to', 'shanghai'),
                    ('weather_to', 'shenzhen'),
                    ('weather_to', 'tianjin'),
                    ('weather_to', 'wuhan'),
                    ('weather_to', 'xian'),
                    ('temperature_from', 'beijing'),
                    ('temperature_from', 'chengdu'),
                    ('temperature_from', 'chongqing'),
                    ('temperature_from', 'guangzhou'),
                    ('temperature_from', 'hangzhou'),
                    ('temperature_from', 'nanjing'),
                    ('temperature_from', 'shanghai'),
                    ('temperature_from', 'shenzhen'),
                    ('temperature_from', 'tianjin'),
                    ('temperature_from', 'wuhan'),
                    ('temperature_from', 'xian'),
                    ('temperature_to', 'beijing'),
                    ('temperature_to', 'chengdu'),
                    ('temperature_to', 'chongqing'),
                    ('temperature_to', 'guangzhou'),
                    ('temperature_to', 'hangzhou'),
                    ('temperature_to', 'nanjing'),
                    ('temperature_to', 'shanghai'),
                    ('temperature_to', 'shenzhen'),
                    ('temperature_to', 'tianjin'),
                    ('temperature_to', 'wuhan'),
                    ('temperature_to', 'xian'),
                    ('wind_direction_from', 'beijing'),
                    ('wind_direction_from', 'chengdu'),
                    ('wind_direction_from', 'chongqing'),
                    ('wind_direction_from', 'guangzhou'),
                    ('wind_direction_from', 'hangzhou'),
                    ('wind_direction_from', 'nanjing'),
                    ('wind_direction_from', 'shanghai'),
                    ('wind_direction_from', 'shenzhen'),
                    ('wind_direction_from', 'tianjin'),
                    ('wind_direction_from', 'wuhan'),
                    ('wind_direction_from', 'xian'),
                    ('wind_direction_to', 'beijing'),
                    ('wind_direction_to', 'chengdu'),
                    ('wind_direction_to', 'chongqing'),
                    ('wind_direction_to', 'guangzhou'),
                    ('wind_direction_to', 'hangzhou'),
                    ('wind_direction_to', 'nanjing'),
                    ('wind_direction_to', 'shanghai'),
                    ('wind_direction_to', 'shenzhen'),
                    ('wind_direction_to', 'tianjin'),
                    ('wind_direction_to', 'wuhan'),
                    ('wind_direction_to', 'xian')]
        },
        "shuffle": True,
        "num_epoch": 20,
        "batch_size": 32,
        "step": 1,
        "split": [0, 0.6, 0.8, 1]
    }
}
